### ISSUE TITLE
That truely helps?

### ISSUE THREAD

**Issue by opto** [rsjtdrjgfuzkfg/thunderbird-experiments#1]
Dirk, did you test whether that truely helps?
I still have multiple occasions where that is not sufficient, and where a restart of TB with the command line option is needed. Actually, I think I once looked in searchfox for the observer message and didn't find it, so I am not sure whether that is still up to date.

Klaus

**Comment by rsjtdrjgfuzkfg** [comment]
@opto Not sure what experiment you are asking about; this repository contains multiple ones.

Maybe CachingFix? In that case: yes, it truly helps; at least in 78.0 where I did my tests. Without clearing the caches and unloading JSMs, updates do not work properly. But you must include the experiment in the very first version of the add-on you ever release, as it fixes caching issues while unloading (and not while loading!).

There are also still usages in searchfox, for example https://searchfox.org/mozilla-central/source/toolkit/components/extensions/ExtensionParent.jsm#1793 – Not sure what you looked for?

**Comment by rsjtdrjgfuzkfg** [comment]
Closing, as this was a question and there seems to be no further need to discuss.
