### ISSUE TITLE
e10s seems to break customUI

### ISSUE THREAD

**Issue by jobisoft** [rsjtdrjgfuzkfg/thunderbird-experiments#4]
I get a permission error for the tab (but not always), and the page is not loaded. If I disable e10s (toggling `browser.tabs.remote.autostart` preference to `false`) it works. I have no idea where to start looking.

A example add-on to reproduce this can be found here:
https://thunderbird.topicbox.com/groups/addons/T2dc009a0e61b16be-Me815561e48a123e2eca733a7/thunderbird-compose-message-create-a-sidebar-for-the-add-on

Any idea?

**Comment by rsjtdrjgfuzkfg** [comment]
Yes, I did not really care about e10s-specific attributes when initializing the browser because it was not yet possible to test them. Should be fixed by 11232201ff437e7bb293efdcb93ecc3963a8328d?
